version: 3

tasks:
  build:
    desc: Build the plugin
    cmds:
      - go build -ldflags "-X 'xiam.li/meta.version=$(gitversion)' -X 'xiam.li/meta.sha=$(git rev-parse HEAD)' -X 'xiam.li/meta.date=$(date -R)'" -o protoc-gen-go-nats cmd/*.go
  run:
    desc: Run the plugin
    cmds:
      - go run -ldflags "-X 'xiam.li/meta.version=$(gitversion)' -X 'xiam.li/meta.sha=$(git rev-parse HEAD)' -X 'xiam.li/meta.date=$(date -R)'" cmd/*.go -v
  install:
    desc: Install the plugin
    deps:
      - build
    cmds:
      - cp protoc-gen-go-nats ~/go/bin/protoc-gen-go-nats
  proto:
    desc: Regenerate protobuf files
    cmds:
      - protoc -I proto --go_out=proto --go_opt=paths=source_relative proto/go_nats.proto
