version: 3

tasks:
  build:
    desc: Build the plugin
    cmds:
    - go build -ldflags "-X 'jdk.sh/meta.version=$(gitversion)' -X 'jdk.sh/meta.sha=$(git rev-parse HEAD)' -X 'jdk.sh/meta.date=$(date -R)'" -o protoc-gen-go-nats cmd/*.go
  install:
    desc: Install the plugin
    deps:
      - build
    cmds:
      - cp protoc-gen-go-nats ~/go/bin/protoc-gen-go-nats
  proto:
    desc: Regenerate protobuf files
    cmds:
      - protoc -I proto --go_out=proto --go_opt=paths=source_relative proto/go_nats.proto
